class EC(object):
    CONFIG_INVALID_TYPE = "CONFIG.INVALID_TYPE"
    CONFIG_MISSING_FIELD = "CONFIG.MISSING_FIELD"
    CONFIG_CONSTRAINT = "CONFIG.CONSTRAINT_VIOLATION"
    CONFIG_UNKNOWN_KEY = "CONFIG.UNKNOWN_KEY"

    MANIFEST_WRITE_FAILED = "MANIFEST.WRITE_FAILED"
    MANIFEST_READ_FAILED = "MANIFEST.READ_FAILED"
    MANIFEST_SCHEMA_MISMATCH = "MANIFEST.SCHEMA_MISMATCH"
    MANIFEST_HASH_MISMATCH = "MANIFEST.HASH_MISMATCH"

    DATA_SPLIT_FAILED = "DATA.SPLIT_FAILED"
    DATA_ITERATION_FAILED = "DATA.ITERATION_FAILED"
    DATA_SCHEMA_MISMATCH = "DATA.SCHEMA_MISMATCH"
    DATA_NOT_FOUND = "DATA.NOT_FOUND"

    ENGINE_STAGE_FAILED = "ENGINE.STAGE_FAILED"
    ENGINE_STEP_FAILED = "ENGINE.STEP_FAILED"
    ENGINE_NAN_LOSS = "ENGINE.NAN_LOSS"
    ENGINE_BAD_STATE = "ENGINE.BAD_STATE"

    ARTIFACT_NOT_FOUND = "ARTIFACT.NOT_FOUND"
    ARTIFACT_WRITE_FAILED = "ARTIFACT.WRITE_FAILED"
    ARTIFACT_READ_FAILED = "ARTIFACT.READ_FAILED"
    ARTIFACT_CORRUPTED = "ARTIFACT.CORRUPTED"
    ARTIFACT_INVALID_KIND = "ARTIFACT.INVALID_KIND"

    CKPT_SAVE_FAILED = "CKPT.SAVE_FAILED"
    CKPT_LOAD_FAILED = "CKPT.LOAD_FAILED"
    CKPT_INCOMPATIBLE = "CKPT.INCOMPATIBLE_STATE"

    METRIC_INVALID_VALUE = "METRIC.INVALID_VALUE"
    METRIC_REDUCTION_FAILED = "METRIC.REDUCTION_FAILED"

    LOG_SINK_FAILED = "LOG.SINK_FAILED"

    REPRO_SEED_NOT_SET = "REPRO.SEED_NOT_SET"
    REPRO_SNAPSHOT_FAILED = "REPRO.SNAPSHOT_FAILED"

    INTERNAL = "INTERNAL.ERROR"
